// <auto-generated />
using System;
using DrumTuner.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DrumTuner.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260522040135_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("DrumTuner.Models.Drum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DrumTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Drums");
                });

            modelBuilder.Entity("DrumTuner.Models.DrumType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultNote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LugCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DrumTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Snare",
                            DefaultNote = "D3",
                            LugCount = 8,
                            Name = "Standard Snare"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Tom",
                            DefaultNote = "C3",
                            LugCount = 6,
                            Name = "Rack Tom"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Tom",
                            DefaultNote = "G2",
                            LugCount = 8,
                            Name = "Floor Tom"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Kick",
                            DefaultNote = "C2",
                            LugCount = 6,
                            Name = "Bass Drum"
                        });
                });

            modelBuilder.Entity("DrumTuner.Models.Instrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InstrumentTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StringNotes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.HasKey("Id");

                    b.ToTable("Instruments");
                });

            modelBuilder.Entity("DrumTuner.Models.InstrumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultNotes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<double>("MaxFrequency")
                        .HasColumnType("REAL");

                    b.Property<double>("MinFrequency")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("StringCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("InstrumentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Guitar",
                            DefaultNotes = "[\"E2\",\"A2\",\"D3\",\"G3\",\"B3\",\"E4\"]",
                            MaxFrequency = 1318.0,
                            MinFrequency = 82.0,
                            Name = "Acoustic Guitar",
                            StringCount = 6
                        },
                        new
                        {
                            Id = 2,
                            Category = "Guitar",
                            DefaultNotes = "[\"E2\",\"A2\",\"D3\",\"G3\",\"B3\",\"E4\"]",
                            MaxFrequency = 1318.0,
                            MinFrequency = 82.0,
                            Name = "Electric Guitar",
                            StringCount = 6
                        },
                        new
                        {
                            Id = 3,
                            Category = "Guitar",
                            DefaultNotes = "[\"B1\",\"E2\",\"A2\",\"D3\",\"G3\",\"B3\",\"E4\"]",
                            MaxFrequency = 1318.0,
                            MinFrequency = 58.0,
                            Name = "7-String Guitar",
                            StringCount = 7
                        },
                        new
                        {
                            Id = 4,
                            Category = "Bass",
                            DefaultNotes = "[\"E1\",\"A1\",\"D2\",\"G2\"]",
                            MaxFrequency = 392.0,
                            MinFrequency = 41.0,
                            Name = "4-String Bass",
                            StringCount = 4
                        },
                        new
                        {
                            Id = 5,
                            Category = "Bass",
                            DefaultNotes = "[\"B0\",\"E1\",\"A1\",\"D2\",\"G2\"]",
                            MaxFrequency = 392.0,
                            MinFrequency = 37.0,
                            Name = "5-String Bass",
                            StringCount = 5
                        },
                        new
                        {
                            Id = 6,
                            Category = "Bass",
                            DefaultNotes = "[\"B0\",\"E1\",\"A1\",\"D2\",\"G2\",\"C3\"]",
                            MaxFrequency = 490.0,
                            MinFrequency = 37.0,
                            Name = "6-String Bass",
                            StringCount = 6
                        },
                        new
                        {
                            Id = 7,
                            Category = "Piano",
                            DefaultNotes = "[\"A0\",\"A#0\",\"B0\",\"C1\",\"C#1\",\"D1\",\"D#1\",\"E1\",\"F1\",\"F#1\",\"G1\",\"G#1\",\"A1\",\"A#1\",\"B1\",\"C2\",\"C#2\",\"D2\",\"D#2\",\"E2\",\"F2\",\"F#2\",\"G2\",\"G#2\",\"A2\",\"A#2\",\"B2\",\"C3\",\"C#3\",\"D3\",\"D#3\",\"E3\",\"F3\",\"F#3\",\"G3\",\"G#3\",\"A3\",\"A#3\",\"B3\",\"C4\",\"C#4\",\"D4\",\"D#4\",\"E4\",\"F4\",\"F#4\",\"G4\",\"G#4\",\"A4\",\"A#4\",\"B4\",\"C5\",\"C#5\",\"D5\",\"D#5\",\"E5\",\"F5\",\"F#5\",\"G5\",\"G#5\",\"A5\",\"A#5\",\"B5\",\"C6\",\"C#6\",\"D6\",\"D#6\",\"E6\",\"F6\",\"F#6\",\"G6\",\"G#6\",\"A6\",\"A#6\",\"B6\",\"C7\",\"C#7\",\"D7\",\"D#7\",\"E7\",\"F7\",\"F#7\",\"G7\",\"G#7\",\"A7\",\"A#7\",\"B7\"]",
                            MaxFrequency = 4186.0,
                            MinFrequency = 27.5,
                            Name = "Piano (88 keys)",
                            StringCount = 88
                        },
                        new
                        {
                            Id = 8,
                            Category = "Strings",
                            DefaultNotes = "[\"G3\",\"D4\",\"A4\",\"E5\"]",
                            MaxFrequency = 1318.0,
                            MinFrequency = 196.0,
                            Name = "Violin",
                            StringCount = 4
                        },
                        new
                        {
                            Id = 9,
                            Category = "Strings",
                            DefaultNotes = "[\"G3\",\"D4\",\"A4\",\"E5\"]",
                            MaxFrequency = 1318.0,
                            MinFrequency = 196.0,
                            Name = "Viola",
                            StringCount = 4
                        },
                        new
                        {
                            Id = 10,
                            Category = "Strings",
                            DefaultNotes = "[\"G2\",\"D3\",\"A3\",\"E4\"]",
                            MaxFrequency = 659.0,
                            MinFrequency = 98.0,
                            Name = "Cello",
                            StringCount = 4
                        },
                        new
                        {
                            Id = 11,
                            Category = "Strings",
                            DefaultNotes = "[\"E1\",\"A1\",\"D2\",\"G2\"]",
                            MaxFrequency = 392.0,
                            MinFrequency = 41.0,
                            Name = "Double Bass",
                            StringCount = 4
                        },
                        new
                        {
                            Id = 12,
                            Category = "Other",
                            DefaultNotes = "[\"G4\",\"C4\",\"E4\",\"A4\"]",
                            MaxFrequency = 880.0,
                            MinFrequency = 262.0,
                            Name = "Ukulele (Standard)",
                            StringCount = 4
                        },
                        new
                        {
                            Id = 13,
                            Category = "Other",
                            DefaultNotes = "[\"G4\",\"D3\",\"G3\",\"B3\",\"D4\"]",
                            MaxFrequency = 1175.0,
                            MinFrequency = 262.0,
                            Name = "Banjo (5-string)",
                            StringCount = 5
                        },
                        new
                        {
                            Id = 14,
                            Category = "Other",
                            DefaultNotes = "[\"G3\",\"D4\",\"G4\",\"B4\",\"E5\"]",
                            MaxFrequency = 1318.0,
                            MinFrequency = 196.0,
                            Name = "Mandolin",
                            StringCount = 8
                        },
                        new
                        {
                            Id = 15,
                            Category = "Other",
                            DefaultNotes = "[\"G2\",\"B2\",\"D3\",\"G3\",\"B3\",\"D4\"]",
                            MaxFrequency = 1175.0,
                            MinFrequency = 98.0,
                            Name = "Dobro",
                            StringCount = 6
                        },
                        new
                        {
                            Id = 16,
                            Category = "Percussion",
                            DefaultNotes = "[\"C3\"]",
                            MaxFrequency = 500.0,
                            MinFrequency = 40.0,
                            Name = "Timpani",
                            StringCount = 1
                        },
                        new
                        {
                            Id = 17,
                            Category = "Percussion",
                            DefaultNotes = "[\"D3\",\"A2\"]",
                            MaxFrequency = 400.0,
                            MinFrequency = 80.0,
                            Name = "Tuned Congas",
                            StringCount = 2
                        });
                });

            modelBuilder.Entity("DrumTuner.Models.Lug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DrumId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TunedNote")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DrumId");

                    b.ToTable("Lugs");
                });

            modelBuilder.Entity("DrumTuner.Models.LugTuningRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TuningSessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TuningSessionId");

                    b.ToTable("LugTuningRecords");
                });

            modelBuilder.Entity("DrumTuner.Models.TuningSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DrumTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TuningSessions");
                });

            modelBuilder.Entity("DrumTuner.Models.Lug", b =>
                {
                    b.HasOne("DrumTuner.Models.Drum", null)
                        .WithMany()
                        .HasForeignKey("DrumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DrumTuner.Models.LugTuningRecord", b =>
                {
                    b.HasOne("DrumTuner.Models.TuningSession", null)
                        .WithMany("LugTuningRecords")
                        .HasForeignKey("TuningSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DrumTuner.Models.TuningSession", b =>
                {
                    b.Navigation("LugTuningRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
